config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'projects#index'
  resources :projects do
    resources :texts, only: [:index]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  validates :name, presence: true

  belongs_to :user
  has_many :texts, dependent: :destroy

  accepts_nested_attributes_for :texts
end

app/models/text.rb
# frozen_string_literal: true

class Text < ApplicationRecord
  validates :key, presence: true
  belongs_to :project
  has_many :translations, dependent: :destroy

  accepts_nested_attributes_for :translations
end

app/models/translation.rb
# frozen_string_literal: true

class Translation < ApplicationRecord
  belongs_to :text
  validates :locale, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable, :trackable

  has_many :projects, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy]

  def index
    @projects = current_user.projects
  end

  def show; end

  def new
    @project = current_user.projects.new
  end

  def edit; end

  def create
    @project = current_user.projects.new(project_params)

    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully destroyed.'
  end

  private

  def set_project
    @project = current_user.projects.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, texts_attributes: [:id, { translations_attributes: %i[id value] }])
  end
end

app/controllers/texts_controller.rb
# frozen_string_literal: true

class TextsController < ApplicationController
  def index
    @project = Project.find(params[:project_id])
    @texts = @project.texts.all
    @locales = %w[en pt]
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Translator
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta content="width=device-width,initial-scale=1" name="viewport" /
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body.bg-gray-50
    .messages
      = notice
    = yield

app/views/projects/_form.html.slim
= form_for @project do |f|
  - if @project.errors.any?
    #error_explanation
      h2 = "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      ul
        - @project.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name, class: 'border border-gray-300 rounded-sm'
  .actions = f.submit class: 'border border-gray-300 rounded-sm py-1 px-3 mr-2'

app/views/projects/edit.html.slim
h1 Editing project

== render 'form'

=> link_to 'Show', @project
'|
=< link_to 'Back', projects_path

app/views/projects/index.html.slim
.container.mx-auto.pt-10
  h1.text-3xl.mb-3 Listing projects
  - @projects.each do |project|
    .border-b.border-gray-300.py-2.flex
      .flex-grow.text-2xl= project.name
      .self-center
        = link_to 'Show', project, class: 'border border-gray-300 rounded-sm py-1 px-3 mr-2'
        = link_to 'Texts', project_texts_path(project), class: 'border border-gray-300 rounded-sm py-1 px-3 mr-2'
        = link_to 'Edit', edit_project_path(project), class: 'border border-gray-300 rounded-sm py-1 px-3 mr-2'
        = link_to 'Destroy', project, data: { confirm: 'Are you sure?' }, method: :delete, class: 'border border-gray-300 rounded-sm py-1 px-3'

  = link_to 'New Project', new_project_path

app/views/projects/new.html.slim
h1 New project

== render 'form'

= link_to 'Back', projects_path

app/views/projects/show.html.slim
p
  strong Name:
  = @project.name

=> link_to 'Edit', edit_project_path(@project)
'|
=< link_to 'Back', projects_path

app/views/texts/index.html.slim
.container.mx-auto
  h1.text-3xl.mb-3 Texts
  .grid.grid-cols-3.border-b.border-gray-300.py-2
    div Identifier
    - @locales.each do |locale|
      div= locale
  = form_for @project do |f|
    = f.fields_for :texts, @texts do |text|
      .grid.grid-cols-3.py-2
        .col-auto= text.object.key
        = text.fields_for :translations do |translation|
          .col-auto= translation.text_field :value, class: 'border border-gray-300 rounded-sm'
    .actions= f.submit class: 'border border-gray-300 rounded-sm py-1 px-3 mr-2'